/*
 * Copyright (c) 2010-2026 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.boschxmpp.internal.protocol;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HexFormat;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.junit.jupiter.api.Test;

/**
 * Tests EasyControl encryption against vectors generated by bosch-xmpp 2.0.0.
 *
 * @author Ondrej Pecta - Initial contribution
 */
@NonNullByDefault
class EasyControlCryptoTest {

    @Test
    void derivesExpectedKeyAndIgnoresAccessKeyHyphens() throws BoschXmppException {
        EasyControlCrypto crypto = new EasyControlCrypto("abcd-efgh-ijkl-mnop", "test-password");

        assertArrayEquals(HexFormat.of().parseHex("59dcaa609db14905b87ee06015e584ea88e46bb95fdda11487d3a78374f9a236"),
                crypto.getKey());
    }

    @Test
    void encryptsAndDecryptsExpectedPayload() throws BoschXmppException {
        EasyControlCrypto crypto = new EasyControlCrypto("abcdefghijklmnop", "test-password");

        String encrypted = crypto.encrypt("{\"value\":20.5}");

        assertEquals("Mvi1K4QaXvQVLU2z+8ptMA==", encrypted);
        assertEquals("{\"value\":20.5}", crypto.decrypt(encrypted));
    }

    @Test
    void rejectsInvalidCiphertextLength() throws BoschXmppException {
        EasyControlCrypto crypto = new EasyControlCrypto("abcdefghijklmnop", "test-password");

        BoschXmppException exception = assertThrows(BoschXmppException.class, () -> crypto.decrypt("AQID"));

        assertEquals(BoschXmppException.Reason.DECRYPTION, exception.getReason());
    }
}
